import config
import logging
import json
from typing import Dict, Any, List

from bot.slack.client import slack_web_client
from bot.models.incident import db_read_incident

logger = logging.getLogger("slack.canvas")

def get_channel_messages(channel_id: str, limit: int = 100) -> List[Dict[str, Any]]:
    """
    Retrieve messages from a Slack channel
    
    Args:
        channel_id: The ID of the channel to retrieve messages from
        limit: Maximum number of messages to retrieve (default: 100)
        
    Returns:
        List of message objects
    """
    try:
        result = slack_web_client.conversations_history(
            channel=channel_id,
            limit=limit
        )
        return result["messages"]
    except Exception as e:
        logger.error(f"Error retrieving channel messages: {e}")
        return []

def summarize_channel_text(messages: List[Dict[str, Any]]) -> str:
    """
    Create a summary of channel messages
    
    This is a simple implementation that extracts key information from messages.
    In a production environment, you might want to use a more sophisticated 
    summarization approach or integrate with an AI service.
    
    Args:
        messages: List of message objects from the channel
        
    Returns:
        Markdown formatted summary text
    """
    if not messages:
        return "No messages found in the channel."
    
    # Filter out bot messages, system messages, etc.
    user_messages = [msg for msg in messages if 'user' in msg and 'text' in msg and not msg.get('bot_id')]
    
    if not user_messages:
        return "No user messages found in the channel."
    
    # Create a simple summary
    summary = "# Incident Channel Summary\n\n"
    
    # Add the most recent messages (limited to 10 for brevity)
    summary += "## Recent Key Messages\n\n"
    for msg in user_messages[:10]:
        user_id = msg.get('user', 'Unknown')
        try:
            # Get user info
            user_info = slack_web_client.users_info(user=user_id)
            user_name = user_info['user']['real_name']
        except Exception:
            user_name = f"<@{user_id}>"
        
        text = msg.get('text', '')
        summary += f"- **{user_name}**: {text}\n\n"
    
    # Add statistics
    summary += "## Channel Statistics\n\n"
    summary += f"- Total messages: {len(messages)}\n"
    summary += f"- User messages: {len(user_messages)}\n"
    
    # Add timestamp of the summary
    summary += "\n\n_This summary was automatically generated by Incident Bot._"
    
    return summary

def create_or_update_channel_canvas(channel_id: str) -> Dict[str, Any]:
    """
    Create or update a Canvas for a channel with a summary of the channel text
    
    Args:
        channel_id: The ID of the channel
        
    Returns:
        Response from the Slack API
    """
    try:
        # Get incident data
        incident_data = db_read_incident(channel_id=channel_id)
        channel_name = incident_data.channel_name
        
        # Get channel messages
        messages = get_channel_messages(channel_id)
        
        # Generate summary
        summary = summarize_channel_text(messages)
        
        # Check if a canvas already exists for this channel
        try:
            # List canvases for the channel
            canvases = slack_web_client.conversations_canvases_list(channel_id=channel_id)
            
            if canvases and canvases.get('canvases') and len(canvases['canvases']) > 0:
                # Update existing canvas
                canvas_id = canvases['canvases'][0]['canvas_id']
                response = slack_web_client.canvases_edit(
                    canvas_id=canvas_id,
                    changes=[{
                        "operation": "replace_all",
                        "document_content": {
                            "type": "markdown",
                            "markdown": summary
                        }
                    }]
                )
                logger.info(f"Updated existing canvas for channel {channel_name}")
                return response
            else:
                # Create new canvas
                response = slack_web_client.conversations_canvases_create(
                    channel_id=channel_id,
                    title=f"Incident Summary: {channel_name}",
                    document_content={
                        "type": "markdown",
                        "markdown": summary
                    }
                )
                logger.info(f"Created new canvas for channel {channel_name}")
                return response
        except Exception as e:
            # If there's an error checking for existing canvases, create a new one
            logger.error(f"Error checking for existing canvases: {e}")
            response = slack_web_client.conversations_canvases_create(
                channel_id=channel_id,
                title=f"Incident Summary: {channel_name}",
                document_content={
                    "type": "markdown",
                    "markdown": summary
                }
            )
            logger.info(f"Created new canvas for channel {channel_name}")
            return response
            
    except Exception as e:
        logger.error(f"Error creating/updating channel canvas: {e}")
        return {"error": str(e)} 